typography:
  h1:
  h2:
  h3:
  h4:
  h5:
  h6:
  p:
  body:
    font-family: Inter
    sizes:

layout:
  banner: bg-purple-100 sticky top-0 border-purple-500 p-3 border
  header:
  body:
  main:
  page:
  sidebar:
  sidebar_indicator:
  aside:
  footer:
  sidebar_toggler:
  sidebar_toggler_icon:
  # Menu item with indicator as an animated highlight
  # menu_item:
  #   default: hover:bg-trasparent dark:hover:bg-transparent
  #   active: bg-transparent hover:bg-transparent dark:bg-transparent dark:hover:bg-transparent
  #   indicator:
  #     default: ml-2 border border-primary-300/20 duration-500 bg-primary-50 dark:bg-primary-500/30 visible z-[-1]
  #     active: w-full transition-all duration-500

  menu_item:
    default:
    # active: bg-transparent dark:bg-transparent text-primary hover:bg-transparent dark:hover:bg-transparent
    indicator:
      # Menu item with indicator as a dot
      # default: visible w-2.5 h-2.5 border-2 border-white dark:border-black -left-[9.3px]
      # default: visible
      active:
  menu_group:
    wrapper:
    header:
      default:
      active:
    # content: border-l

common:
  # icon_size: 40
  # border_color:
  # foreground_color:
  border_radius:
    # sm: rounded-[4px]
    # md: rounded-md
    # lg: rounded-lg
  # dropdown:
  #   arrow_trailing_icon: solar:alt-arrow-right-bold
  #   content: p-0 rounded-none border-black
  #   separator: my-0 bg-black mx-0
  #   item: rounded-none hover:bg-primary-50 focus:bg-primary focus:text-white
  tab:
    class:
    outer_radius: # defaults to true
    title:
    panel:
    root:
    list:

colors:
  primary:
    DEFAULT: "#34d399"
    50: "#ecfdf5"
    100: "#d1fae5"
    200: "#a7f3d0"
    300: "#6ee7b7"
    400: "#34d399"
    500: "#10b981"
    600: "#059669"
    700: "#047857"
    800: "#065f46"
    900: "#064e3b"
    950: "#022c22"
#   gray:
#     DEFAULT: '#6b7280'
#     50: '#f9fafb'
#     100: '#f3f4f6'
#     200: '#e5e7eb'
#     300: '#d1d5db'
#     400: '#9ca3af'
#     500: '#6b7280'
#     600: '#4b5563'
#     700: '#374151'
#     800: '#1f2937'
#     900: '#111827'
#     950: '#030712'
#   destructive:
#     DEFAULT: '#EF4444'
#     50: '#FEF2F2'
#     100: '#FEE2E2'
#     200: '#FECACA'
#     300: '#FCA5A5'
#     400: '#F87171'
#     500: '#EF4444'
#     600: '#DC2626'
#     700: '#B91C1C'
#     800: '#991B1B'
#     900: '#7F1D1D'
#     950: '#450A0A'
#   positive:
#     DEFAULT: '#10B981'
#     50: '#ECFDF5'
#     100: '#D1FAE5'
#     200: '#A7F3D0'
#     300: '#6EE7B7'
#     400: '#34D399'
#     500: '#10B981'
#     600: '#059669'
#     700: '#047857'
#     800: '#065F46'
#     900: '#064E3B'
#     950: '#022c22'

forms:
  common:
    default_size: md
    sizes:
      sm: # h-6
      md: # h-8
      lg: h-12 px-4 text-base # custom size
    border_radius:
      sm: #rounded-none
      md: #rounded-none
      lg: rounded-lg # custom size
  button:
    variants:
      filled:
      outline:
      ghost:
      link:
