# start a job on release
name: Deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      - name: Deploy to Railway
        run: railway up --service fluwy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
