name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Capture New Release Version
        run: |
          pnpm changeset status --output=release.json
          echo "NEW_VERSION=$(jq -r '.releases[] | select(.name=="@fluwy/ui") | .newVersion' release.json)" >> "$GITHUB_ENV"
          rm release.json

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: "Release v${{env.NEW_VERSION}}"
          commit: "Release v${{env.NEW_VERSION}}"
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
